[project]
name = "tdsot-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.15.0",
    "scrapy>=2.18.0",
    "scrapy-poet>=0.27.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.411",
    "ruff>=0.16.5",
]

[tool.ruff.format]
quote-style = "single"
